name: Ruby CI

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'  # Or the version you are using
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run tests
      run: rspec
